default: &default
  adapter: postgresql

development:
  <<: *default
  database: blogit_dev

production:
  <<: *default
  database: blogit

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
